language: C

addons:
  apt:
    packages:
    - build-essential
    - g++-arm-linux-gnueabihf
    - gcc-arm-linux-gnueabihf
    - qemu

compiler:
  - arm-linux-gnueabihf-gcc

script: 
  - make clean
  - make
  - make debug
  - sudo qemu-arm -L /usr/arm-linux-gnueabihf/ rpi3tester -v
