language: C
sudo: required
dist: trusty

addons:
  apt:
    packages:
    - make
    - g++-arm-linux-gnueabihf
    - gcc-arm-linux-gnueabihf
    - qemu
    - qemu-system-arm

compiler:
  - arm-linux-gnueabihf-gcc

script: 
  - make
  - make debug
  - sudo qemu-arm -L /usr/arm-linux-gnueabihf/ rpi3tester -v
  - make clean
